### ISSUE TITLE
Implement Document.validate()

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#155]
Document.validate() is not implemented yet. Implement it. It may also need to be tied in to Document.write() for backward compatibility with pysbol.

```
>>> doc.validate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bbartley/Dev/git/pySBOL2/sbol2/document.py", line 681, in validate
    raise NotImplementedError("Not yet implemented")
NotImplementedError: Not yet implemented
```

**Comment by tcmitchell** [comment]
SD2.Bree uses Document.validate in src/design/sbol_parser.py. Let her know when this is implemented.
