### ISSUE TITLE
Cannot set CD.sequence to string

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#317]
The documentation (getting_started) shows the following example:

```
>>> eyfp_gene.sequence = seq.identity
>>> print (eyfp_gene.sequence)
'http://sbols.org/Sequence/EYFPSequence/1.0.0'
```

Which results in an error:

```
>>> eyfp_gene.sequence = seq.identity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tmitchel/Projects/sd2/pySBOL2/sbol2/object.py", line 459, in __setattr__
    object.__setattr__(self, name, value)
  File "/Users/tmitchel/Projects/sd2/pySBOL2/sbol2/componentdefinition.py", line 176, in sequence
    self.sequences = [sequence.identity]
AttributeError: 'str' object has no attribute 'identity'
```

**Comment by bbartley** [comment]
I don't think this is a problem with the library implementation, likely just a documentation error
